version: "3"
services:
  redis-server:
    image: 'redis'
  node-application:
    build:
      context: ./
      target: dev
    ports:
      - "8090:8090"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command:
      ["npm", "start"]
  node-test:
    build: .
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "test"]